import type { Vehicle, Testimonial, FAQItem, ProcessStep, Feature } from "@/types";

export const vehicles: Vehicle[] = [
  {
    id: "byd-seal",
    slug: "byd-seal",
    brand: "BYD",
    model: "Seal",
    year: 2024,
    price: 28800,
    fuel: "Electric",
    bodyType: "Sedan",
    transmission: "Single-Speed",
    image: "/cars/byd-seal.png",
    images: ["/cars/byd-seal.png", "/vehicles/byd-seal-rear.jpg", "/vehicles/byd-seal-interior.jpg"],
    badge: "New",
    range: "570 km",
    engine: "Dual Motor AWD",
    description:
      "The BYD Seal is a premium electric sedan that combines sleek aerodynamic design with cutting-edge Blade Battery technology. With a CLTC range of 570 km and dual-motor all-wheel drive, it delivers exhilarating performance while maintaining exceptional efficiency. The spacious interior features a 15.6-inch rotating touchscreen, premium leather upholstery, and advanced driver assistance systems. Built on BYD's e-Platform 3.0, the Seal represents the pinnacle of Chinese EV engineering.",
    specs: {
      power: "523 hp (390 kW)",
      torque: "670 Nm",
      acceleration: "3.8s (0-100 km/h)",
      topSpeed: "180 km/h",
      range: "570 km (CLTC)",
      batteryCapacity: "82.5 kWh",
      chargingTime: "30 min (10-80% DC fast)",
      drivetrain: "AWD",
      length: "4,800 mm",
      width: "1,875 mm",
      height: "1,460 mm",
      wheelbase: "2,920 mm",
      weight: "2,050 kg",
      seatingCapacity: 5,
      bootSpace: "400 L",
    },
    features: [
      "Blade Battery Technology",
      "15.6-inch Rotating Touchscreen",
      "Dual Motor AWD",
      "ADAS Level 2",
      "Panoramic Sunroof",
      "Leather Seats with Heating & Ventilation",
      "12-speaker Dynaudio Sound System",
      "OTA Software Updates",
      "Wireless Phone Charging",
      "Ambient Lighting (256 colors)",
    ],
    colors: ["Polar White", "Cosmic Black", "Aurora Green", "Deep Blue"],
    condition: "New",
    availability: "In Stock",
  },
  {
    id: "toyota-rav4",
    slug: "toyota-rav4",
    brand: "Toyota",
    model: "RAV4",
    year: 2024,
    price: 22500,
    fuel: "Hybrid",
    bodyType: "SUV",
    transmission: "Automatic",
    image: "/vehicles/rav4.jpg",
    images: ["/vehicles/rav4.jpg", "/vehicles/rav4-rear.jpg", "/vehicles/rav4-interior.jpg"],
    badge: "Popular",
    engine: "2.5L Hybrid",
    description:
      "The Toyota RAV4 Hybrid is the world's best-selling hybrid SUV, known for its legendary reliability and fuel efficiency. Powered by Toyota's proven 2.5L hybrid powertrain, it delivers excellent fuel economy without compromising on performance. The rugged exterior design, spacious interior, and Toyota Safety Sense 2.0 suite make it the perfect family SUV for global buyers. With available AWD-i intelligent all-wheel drive, the RAV4 handles any terrain with confidence.",
    specs: {
      power: "219 hp (163 kW)",
      torque: "221 Nm",
      acceleration: "8.1s (0-100 km/h)",
      topSpeed: "180 km/h",
      fuelEconomy: "5.8 L/100 km",
      engineDisplacement: "2.5L Hybrid",
      drivetrain: "AWD",
      length: "4,600 mm",
      width: "1,855 mm",
      height: "1,685 mm",
      wheelbase: "2,690 mm",
      weight: "1,670 kg",
      seatingCapacity: 5,
      bootSpace: "580 L",
    },
    features: [
      "Toyota Safety Sense 2.0",
      "AWD-i Intelligent All-Wheel Drive",
      "8-inch Touchscreen Infotainment",
      "Apple CarPlay & Android Auto",
      "Power Tailgate",
      "Dual Zone Climate Control",
      "LED Headlights with Auto High Beam",
      "Wireless Phone Charging",
      "JBL Premium Audio (9 speakers)",
      "Panoramic View Monitor",
    ],
    colors: ["Pearl White", "Magnetic Grey", "Ruby Flare", "Attitude Black"],
    condition: "New",
    availability: "In Stock",
  },
  {
    id: "geely-monjaro",
    slug: "geely-monjaro",
    brand: "Geely",
    model: "Monjaro",
    year: 2024,
    price: 18900,
    fuel: "Petrol",
    bodyType: "SUV",
    transmission: "Automatic",
    image: "/vehicles/monjaro.jpg",
    images: ["/vehicles/monjaro.jpg", "/vehicles/monjaro-rear.jpg", "/vehicles/monjaro-interior.jpg"],
    badge: "New",
    engine: "2.0T Turbo",
    description:
      "The Geely Monjaro is a premium mid-size SUV that showcases Geely's ambitious design language and Volvo-derived engineering. Built on the CMA platform shared with Volvo, it offers exceptional ride quality and safety. The 2.0T turbocharged engine delivers smooth power delivery, while the luxurious interior features a massive vertical infotainment screen, Nappa leather seats, and a panoramic sunroof. The Monjaro punches well above its price point, offering flagship-level features at an accessible price.",
    specs: {
      power: "238 hp (175 kW)",
      torque: "350 Nm",
      acceleration: "7.7s (0-100 km/h)",
      topSpeed: "215 km/h",
      fuelEconomy: "7.8 L/100 km",
      engineDisplacement: "2.0L Turbo",
      drivetrain: "AWD",
      length: "4,770 mm",
      width: "1,895 mm",
      height: "1,689 mm",
      wheelbase: "2,842 mm",
      weight: "1,740 kg",
      seatingCapacity: 5,
      bootSpace: "562 L",
    },
    features: [
      "CMA Platform (Volvo-derived)",
      "12.3-inch Vertical Touchscreen",
      "Nappa Leather Seats",
      "Panoramic Sunroof",
      "Bose Premium Audio (12 speakers)",
      "Level 2 Autonomous Driving",
      "360-degree Camera System",
      "Heated & Ventilated Front Seats",
      "Heads-Up Display (HUD)",
      "Air Purification System",
    ],
    colors: ["Crystal White", "Cosmos Blue", "Quantum Grey", "Obsidian Black"],
    condition: "New",
    availability: "In Stock",
  },
  {
    id: "honda-civic",
    slug: "honda-civic",
    brand: "Honda",
    model: "Civic",
    year: 2024,
    price: 17200,
    fuel: "Petrol",
    bodyType: "Sedan",
    transmission: "Automatic",
    image: "/vehicles/civic.jpg",
    images: ["/vehicles/civic.jpg", "/vehicles/civic-rear.jpg", "/vehicles/civic-interior.jpg"],
    engine: "1.5T VTEC",
    description:
      "The Honda Civic needs no introduction — it's one of the most trusted and beloved sedans worldwide. The 2024 Civic features a bold new design with a low, wide stance and a honeycomb dashboard that sets it apart from competitors. The 1.5L VTEC Turbo engine balances power and efficiency perfectly, while Honda Sensing safety suite comes standard. The Civic's reputation for reliability, low maintenance costs, and strong resale value makes it a top choice for first-time importers.",
    specs: {
      power: "180 hp (134 kW)",
      torque: "240 Nm",
      acceleration: "7.9s (0-100 km/h)",
      topSpeed: "200 km/h",
      fuelEconomy: "6.0 L/100 km",
      engineDisplacement: "1.5L VTEC Turbo",
      drivetrain: "FWD",
      length: "4,675 mm",
      width: "1,800 mm",
      height: "1,415 mm",
      wheelbase: "2,735 mm",
      weight: "1,330 kg",
      seatingCapacity: 5,
      bootSpace: "420 L",
    },
    features: [
      "Honda Sensing Safety Suite",
      "9-inch Touchscreen Infotainment",
      "Apple CarPlay & Android Auto",
      "Honeycomb Dashboard Design",
      "Dual Zone Climate Control",
      "LED Headlights & Taillights",
      "Sport Mode with Paddle Shifters",
      "Wireless Phone Charging",
      "8-speaker Audio System",
      "Remote Engine Start",
    ],
    colors: ["Spiral Pearl White", "Sonic Grey", "Rallye Red", "Crystal Black"],
    condition: "New",
    availability: "In Stock",
  },
  {
    id: "byd-han",
    slug: "byd-han",
    brand: "BYD",
    model: "Han EV",
    year: 2024,
    price: 34500,
    fuel: "Electric",
    bodyType: "Sedan",
    transmission: "Single-Speed",
    image: "/vehicles/byd-han.jpg",
    images: ["/vehicles/byd-han.jpg", "/vehicles/byd-han-rear.jpg", "/vehicles/byd-han-interior.jpg"],
    badge: "Premium",
    range: "605 km",
    engine: "Dual Motor AWD",
    description:
      "The BYD Han EV is BYD's flagship luxury electric sedan, designed to compete with the Tesla Model S and Porsche Taycan at a fraction of the price. With a stunning 605 km CLTC range, dual-motor AWD producing 517 hp, and a 0-100 km/h time of 3.9 seconds, the Han EV is a true performance luxury sedan. The interior rivals European luxury brands with Nappa leather, a rotating 15.6-inch touchscreen, and a 12.3-inch digital instrument cluster. The Blade Battery ensures class-leading safety with zero thermal runaway.",
    specs: {
      power: "517 hp (380 kW)",
      torque: "700 Nm",
      acceleration: "3.9s (0-100 km/h)",
      topSpeed: "185 km/h",
      range: "605 km (CLTC)",
      batteryCapacity: "85.4 kWh",
      chargingTime: "25 min (10-80% DC fast)",
      drivetrain: "AWD",
      length: "4,995 mm",
      width: "1,910 mm",
      height: "1,495 mm",
      wheelbase: "2,920 mm",
      weight: "2,100 kg",
      seatingCapacity: 5,
      bootSpace: "410 L",
    },
    features: [
      "Blade Battery (Zero Thermal Runaway)",
      "15.6-inch Rotating Touchscreen",
      "12.3-inch Digital Instrument Cluster",
      "Nappa Leather Interior",
      "Level 2 Autonomous Driving (DiPilot)",
      "DiLink 4.0 Smart Connectivity",
      "12-speaker Dirac Audio System",
      "Massage & Ventilation (Front Seats)",
      "Ambient Lighting (128 colors)",
      "Smart Air Suspension",
    ],
    colors: ["Aurora White", "Cosmic Black", "Ember Red", "Slate Grey"],
    condition: "New",
    availability: "In Stock",
  },
  {
    id: "changan-uni-k",
    slug: "changan-uni-k",
    brand: "Changan",
    model: "UNI-K",
    year: 2024,
    price: 21300,
    fuel: "Petrol",
    bodyType: "SUV",
    transmission: "Automatic",
    image: "/vehicles/uni-k.jpg",
    images: ["/vehicles/uni-k.jpg", "/vehicles/uni-k-rear.jpg", "/vehicles/uni-k-interior.jpg"],
    engine: "2.0T Blue Core",
    description:
      "The Changan UNI-K is a futuristic mid-to-large SUV that turns heads with its boundaryless front grille design and sleek LED lighting signature. Powered by Changan's proven 2.0T Blue Core engine, it delivers refined performance with excellent fuel economy. The interior is a tech lover's dream with dual screens, a futuristic yoke-style steering wheel option, and premium materials throughout. The UNI-K offers flagship SUV space and features at a mid-range price point, making it an exceptional value for global importers.",
    specs: {
      power: "228 hp (171 kW)",
      torque: "360 Nm",
      acceleration: "8.8s (0-100 km/h)",
      topSpeed: "200 km/h",
      fuelEconomy: "8.4 L/100 km",
      engineDisplacement: "2.0L Turbo",
      drivetrain: "AWD",
      length: "4,865 mm",
      width: "1,948 mm",
      height: "1,700 mm",
      wheelbase: "2,890 mm",
      weight: "1,810 kg",
      seatingCapacity: 5,
      bootSpace: "521 L",
    },
    features: [
      "Boundaryless Front Grille Design",
      "Dual 12.3-inch Screens",
      "Level 2 Autonomous Driving (IACC)",
      "Panoramic Sunroof",
      "Sony Premium Audio (14 speakers)",
      "360-degree Panoramic Camera",
      "Heated & Cooled Front Seats",
      "Smart Voice Assistant",
      "APA 6.0 Remote Smart Parking",
      "Forest Air Purification System",
    ],
    colors: ["Stellar White", "Nebula Black", "Atomic Grey", "Mars Red"],
    condition: "New",
    availability: "On Request",
  },
  {
    id: "geely-coolray",
    slug: "geely-coolray",
    brand: "Geely",
    model: "Coolray",
    year: 2024,
    price: 15800,
    fuel: "Petrol",
    bodyType: "SUV",
    transmission: "Automatic",
    image: "/vehicles/coolray.jpg",
    images: ["/vehicles/coolray.jpg"],
    badge: "Hot",
    engine: "1.5T Turbo",
    description:
      "The Geely Coolray is a compact SUV that combines sporty design with advanced technology. Built on the BMA platform, it offers excellent handling and fuel efficiency. The 1.5T turbo engine delivers responsive performance, while the modern interior features a large touchscreen, premium materials, and comprehensive safety features.",
    specs: {
      power: "177 hp (130 kW)",
      torque: "255 Nm",
      acceleration: "8.4s (0-100 km/h)",
      topSpeed: "195 km/h",
      fuelEconomy: "6.8 L/100 km",
      engineDisplacement: "1.5L Turbo",
      drivetrain: "FWD",
      length: "4,330 mm",
      width: "1,800 mm",
      height: "1,609 mm",
      wheelbase: "2,600 mm",
      weight: "1,420 kg",
      seatingCapacity: 5,
      bootSpace: "380 L",
    },
    features: [
      "10.25-inch Touchscreen",
      "360-degree Camera",
      "LED Headlights",
      "Wireless Phone Charging",
      "Panoramic Sunroof",
      "Adaptive Cruise Control",
      "Lane Keep Assist",
      "Automatic Emergency Braking",
    ],
    colors: ["Pearl White", "Titanium Grey", "Energy Red", "Midnight Blue"],
    condition: "New",
    availability: "In Stock",
  },
  {
    id: "byd-tang",
    slug: "byd-tang",
    brand: "BYD",
    model: "Tang EV",
    year: 2024,
    price: 42500,
    fuel: "Electric",
    bodyType: "SUV",
    transmission: "Single-Speed",
    image: "/vehicles/byd-tang.jpg",
    images: ["/vehicles/byd-tang.jpg"],
    badge: "Premium",
    range: "505 km",
    engine: "Dual Motor AWD",
    description:
      "The BYD Tang EV is a flagship 7-seater electric SUV that combines luxury, performance, and practicality. With dual motors producing 517 hp and a 505 km range, it offers supercar acceleration with family car space. The premium interior features Nappa leather, a rotating 15.6-inch screen, and three rows of comfortable seating.",
    specs: {
      power: "517 hp (380 kW)",
      torque: "700 Nm",
      acceleration: "4.4s (0-100 km/h)",
      topSpeed: "180 km/h",
      range: "505 km (CLTC)",
      batteryCapacity: "108.8 kWh",
      chargingTime: "30 min (10-80% DC fast)",
      drivetrain: "AWD",
      length: "4,870 mm",
      width: "1,950 mm",
      height: "1,725 mm",
      wheelbase: "2,820 mm",
      weight: "2,410 kg",
      seatingCapacity: 7,
      bootSpace: "940 L",
    },
    features: [
      "7-Seat Configuration",
      "Blade Battery Technology",
      "15.6-inch Rotating Touchscreen",
      "Nappa Leather Interior",
      "Air Suspension",
      "Level 2 Autonomous Driving",
      "12-speaker Audio System",
      "Panoramic Sunroof",
      "Heated & Ventilated Seats",
      "Power Tailgate",
    ],
    colors: ["Aurora White", "Obsidian Black", "Mercury Grey", "Imperial Red"],
    condition: "New",
    availability: "In Stock",
  },
  {
    id: "changan-cs75",
    slug: "changan-cs75",
    brand: "Changan",
    model: "CS75 Plus",
    year: 2024,
    price: 19500,
    fuel: "Petrol",
    bodyType: "SUV",
    transmission: "Automatic",
    image: "/vehicles/cs75.jpg",
    images: ["/vehicles/cs75.jpg"],
    engine: "2.0T Blue Core",
    description:
      "The Changan CS75 Plus is a mid-size SUV that offers exceptional value with premium features and spacious interior. The 2.0T engine provides strong performance, while the modern design and tech-forward cabin make it a popular choice for families and first-time importers.",
    specs: {
      power: "233 hp (171 kW)",
      torque: "360 Nm",
      acceleration: "8.5s (0-100 km/h)",
      topSpeed: "200 km/h",
      fuelEconomy: "7.5 L/100 km",
      engineDisplacement: "2.0L Turbo",
      drivetrain: "FWD",
      length: "4,700 mm",
      width: "1,865 mm",
      height: "1,710 mm",
      wheelbase: "2,710 mm",
      weight: "1,680 kg",
      seatingCapacity: 5,
      bootSpace: "520 L",
    },
    features: [
      "12.3-inch Touchscreen",
      "360-degree Camera",
      "Panoramic Sunroof",
      "LED Headlights",
      "Wireless Charging",
      "Adaptive Cruise Control",
      "Lane Departure Warning",
      "Automatic Emergency Braking",
    ],
    colors: ["Pearl White", "Titanium Grey", "Ruby Red", "Sapphire Blue"],
    condition: "New",
    availability: "In Stock",
  },
  {
    id: "geely-emgrand",
    slug: "geely-emgrand",
    brand: "Geely",
    model: "Emgrand",
    year: 2024,
    price: 12800,
    fuel: "Petrol",
    bodyType: "Sedan",
    transmission: "Automatic",
    image: "/vehicles/emgrand.jpg",
    images: ["/vehicles/emgrand.jpg"],
    badge: "Value",
    engine: "1.5L DVVT",
    description:
      "The Geely Emgrand is an affordable sedan that delivers excellent value without compromising on quality. Built on Geely's BMA platform, it offers a comfortable ride, modern styling, and a well-equipped interior. Perfect for budget-conscious buyers who want reliability and features.",
    specs: {
      power: "114 hp (84 kW)",
      torque: "147 Nm",
      acceleration: "11.5s (0-100 km/h)",
      topSpeed: "180 km/h",
      fuelEconomy: "5.9 L/100 km",
      engineDisplacement: "1.5L",
      drivetrain: "FWD",
      length: "4,638 mm",
      width: "1,820 mm",
      height: "1,470 mm",
      wheelbase: "2,650 mm",
      weight: "1,250 kg",
      seatingCapacity: 5,
      bootSpace: "450 L",
    },
    features: [
      "10.25-inch Touchscreen",
      "LED Daytime Running Lights",
      "Cruise Control",
      "Rear Parking Sensors",
      "Bluetooth Connectivity",
      "USB Ports",
      "Air Conditioning",
      "Power Windows",
    ],
    colors: ["Pearl White", "Titanium Grey", "Crystal Black", "Ocean Blue"],
    condition: "New",
    availability: "In Stock",
  },
  {
    id: "byd-dolphin",
    slug: "byd-dolphin",
    brand: "BYD",
    model: "Dolphin",
    year: 2024,
    price: 18900,
    fuel: "Electric",
    bodyType: "Hatchback",
    transmission: "Single-Speed",
    image: "/vehicles/byd-dolphin.jpg",
    images: ["/vehicles/byd-dolphin.jpg"],
    badge: "New",
    range: "405 km",
    engine: "Single Motor",
    description:
      "The BYD Dolphin is a compact electric hatchback that combines playful design with practical efficiency. Built on BYD's e-Platform 3.0, it offers impressive range, quick charging, and a surprisingly spacious interior. Perfect for urban driving with zero emissions.",
    specs: {
      power: "204 hp (150 kW)",
      torque: "310 Nm",
      acceleration: "7.0s (0-100 km/h)",
      topSpeed: "160 km/h",
      range: "405 km (CLTC)",
      batteryCapacity: "60.48 kWh",
      chargingTime: "30 min (10-80% DC fast)",
      drivetrain: "FWD",
      length: "4,150 mm",
      width: "1,770 mm",
      height: "1,570 mm",
      wheelbase: "2,700 mm",
      weight: "1,540 kg",
      seatingCapacity: 5,
      bootSpace: "345 L",
    },
    features: [
      "Blade Battery Technology",
      "12.8-inch Rotating Touchscreen",
      "NFC Key Card",
      "Wireless Phone Charging",
      "LED Headlights",
      "Adaptive Cruise Control",
      "360-degree Camera",
      "OTA Updates",
    ],
    colors: ["Polar White", "Cosmic Black", "Coral Pink", "Sky Blue"],
    condition: "New",
    availability: "In Stock",
  },
  {
    id: "toyota-corolla",
    slug: "toyota-corolla",
    brand: "Toyota",
    model: "Corolla",
    year: 2024,
    price: 19800,
    fuel: "Hybrid",
    bodyType: "Sedan",
    transmission: "Automatic",
    image: "/vehicles/corolla.jpg",
    images: ["/vehicles/corolla.jpg"],
    badge: "Popular",
    engine: "1.8L Hybrid",
    description:
      "The Toyota Corolla Hybrid is the world's best-selling nameplate, now with hybrid efficiency. Known for legendary reliability and low running costs, the Corolla Hybrid delivers excellent fuel economy without sacrificing comfort or features. A smart choice for cost-conscious buyers.",
    specs: {
      power: "122 hp (91 kW)",
      torque: "142 Nm",
      acceleration: "10.5s (0-100 km/h)",
      topSpeed: "180 km/h",
      fuelEconomy: "4.3 L/100 km",
      engineDisplacement: "1.8L Hybrid",
      drivetrain: "FWD",
      length: "4,630 mm",
      width: "1,780 mm",
      height: "1,435 mm",
      wheelbase: "2,700 mm",
      weight: "1,370 kg",
      seatingCapacity: 5,
      bootSpace: "470 L",
    },
    features: [
      "Toyota Safety Sense 2.0",
      "8-inch Touchscreen",
      "Apple CarPlay & Android Auto",
      "Adaptive Cruise Control",
      "Lane Tracing Assist",
      "LED Headlights",
      "Dual Zone Climate Control",
      "Wireless Phone Charging",
    ],
    colors: ["Super White", "Celestite Grey", "Attitude Black", "Emotional Red"],
    condition: "New",
    availability: "In Stock",
  },
  {
    id: "honda-cr-v",
    slug: "honda-cr-v",
    brand: "Honda",
    model: "CR-V",
    year: 2024,
    price: 24500,
    fuel: "Hybrid",
    bodyType: "SUV",
    transmission: "Automatic",
    image: "/vehicles/crv.jpg",
    images: ["/vehicles/crv.jpg"],
    badge: "Popular",
    engine: "2.0L Hybrid",
    description:
      "The Honda CR-V Hybrid combines practicality with efficiency. Its spacious interior, advanced safety features, and proven hybrid powertrain make it a top choice for families worldwide.",
    specs: {
      power: "184 hp (137 kW)",
      torque: "315 Nm",
      acceleration: "8.8s (0-100 km/h)",
      topSpeed: "180 km/h",
      fuelEconomy: "5.5 L/100 km",
      engineDisplacement: "2.0L Hybrid",
      drivetrain: "AWD",
      length: "4,694 mm",
      width: "1,864 mm",
      height: "1,683 mm",
      wheelbase: "2,660 mm",
      weight: "1,720 kg",
      seatingCapacity: 5,
      bootSpace: "589 L",
    },
    features: [
      "Honda Sensing Suite",
      "9-inch Touchscreen",
      "Apple CarPlay & Android Auto",
      "Wireless Phone Charging",
      "Panoramic Moonroof",
      "Heated Front Seats",
      "Remote Engine Start",
      "Honda LaneWatch",
    ],
    colors: ["Platinum White", "Lunar Silver", "Crystal Black", "Radiant Red"],
    condition: "New",
    availability: "In Stock",
  },
  {
    id: "changan-uni-t",
    slug: "changan-uni-t",
    brand: "Changan",
    model: "UNI-T",
    year: 2024,
    price: 17200,
    fuel: "Petrol",
    bodyType: "SUV",
    transmission: "Automatic",
    image: "/vehicles/unit.jpg",
    images: ["/vehicles/unit.jpg"],
    badge: "Sporty",
    engine: "1.5T Blue Core",
    description:
      "The Changan UNI-T is a bold, futuristic compact SUV with a distinctive design. Its advanced 1.5T engine and modern tech features make it stand out in its class.",
    specs: {
      power: "188 hp (138 kW)",
      torque: "300 Nm",
      acceleration: "8.5s (0-100 km/h)",
      topSpeed: "195 km/h",
      fuelEconomy: "6.5 L/100 km",
      engineDisplacement: "1.5L Turbo",
      drivetrain: "FWD",
      length: "4,515 mm",
      width: "1,870 mm",
      height: "1,565 mm",
      wheelbase: "2,710 mm",
      weight: "1,510 kg",
      seatingCapacity: 5,
      bootSpace: "410 L",
    },
    features: [
      "10.25-inch Dual Screens",
      "360-degree Camera",
      "Panoramic Sunroof",
      "LED Headlights",
      "Wireless Charging",
      "Adaptive Cruise Control",
      "Lane Keep Assist",
      "Electric Tailgate",
    ],
    colors: ["Pearl White", "Atomic Grey", "Energy Red", "Starry Blue"],
    condition: "New",
    availability: "In Stock",
  },
  {
    id: "geely-monjaro-premium",
    slug: "geely-monjaro-premium",
    brand: "Geely",
    model: "Monjaro Premium",
    year: 2024,
    price: 21800,
    fuel: "Petrol",
    bodyType: "SUV",
    transmission: "Automatic",
    image: "/vehicles/monjaro.jpg",
    images: ["/vehicles/monjaro.jpg"],
    badge: "Premium",
    engine: "2.0T",
    description:
      "The Geely Monjaro is a premium mid-size SUV built on the CMA platform co-developed with Volvo. It offers a refined driving experience, spacious interior, and premium features at an accessible price.",
    specs: {
      power: "238 hp (175 kW)",
      torque: "350 Nm",
      acceleration: "7.9s (0-100 km/h)",
      topSpeed: "210 km/h",
      fuelEconomy: "7.2 L/100 km",
      engineDisplacement: "2.0L Turbo",
      drivetrain: "AWD",
      length: "4,770 mm",
      width: "1,895 mm",
      height: "1,689 mm",
      wheelbase: "2,800 mm",
      weight: "1,750 kg",
      seatingCapacity: 5,
      bootSpace: "510 L",
    },
    features: [
      "12.3-inch Touchscreen",
      "Bose Premium Audio",
      "Panoramic Sunroof",
      "Nappa Leather Seats",
      "360-degree Camera",
      "Adaptive Cruise Control",
      "Heated & Ventilated Seats",
      "Power Tailgate",
    ],
    colors: ["Pearl White", "Titanium Grey", "Crystal Black", "Ruby Red"],
    condition: "New",
    availability: "In Stock",
  },
  {
    id: "byd-han-flagship",
    slug: "byd-han-flagship",
    brand: "BYD",
    model: "Han EV",
    year: 2024,
    price: 35800,
    fuel: "Electric",
    bodyType: "Sedan",
    transmission: "Single-Speed",
    image: "/vehicles/byd-han.jpg",
    images: ["/vehicles/byd-han.jpg"],
    badge: "Flagship",
    range: "610 km",
    engine: "Dual Motor AWD",
    description:
      "The BYD Han EV is BYD's flagship luxury electric sedan. With a 610 km range, 3.9s 0-100 km/h acceleration, and premium interior, it competes with the best luxury EVs globally.",
    specs: {
      power: "517 hp (380 kW)",
      torque: "700 Nm",
      acceleration: "3.9s (0-100 km/h)",
      topSpeed: "185 km/h",
      range: "610 km (CLTC)",
      batteryCapacity: "85.4 kWh",
      chargingTime: "30 min (10-80% DC fast)",
      drivetrain: "AWD",
      length: "4,995 mm",
      width: "1,910 mm",
      height: "1,495 mm",
      wheelbase: "2,920 mm",
      weight: "2,170 kg",
      seatingCapacity: 5,
      bootSpace: "410 L",
    },
    features: [
      "Blade Battery Technology",
      "15.6-inch Rotating Touchscreen",
      "Nappa Leather Interior",
      "12-speaker Dynaudio Audio",
      "Air Suspension",
      "Level 2+ Autonomous Driving",
      "Heated & Ventilated Seats",
      "Panoramic Sunroof",
      "Ambient Lighting (128 colors)",
      "OTA Updates",
    ],
    colors: ["Snow White", "Obsidian Black", "Titanium Grey", "Imperial Red"],
    condition: "New",
    availability: "On Request",
  },

  // ══════════════════════════════════════════════════════════════
  // TRUCKS & COMMERCIAL VEHICLES
  // ══════════════════════════════════════════════════════════════
  {
    id: "sinotruk-howo",
    slug: "sinotruk-howo",
    brand: "Sinotruk",
    model: "HOWO A7",
    year: 2024,
    price: 32000,
    fuel: "Diesel",
    bodyType: "Truck",
    transmission: "Manual",
    image: "/vehicles/sinotruk-howo.jpg",
    images: ["/vehicles/sinotruk-howo.jpg"],
    badge: "Hot",
    engine: "WP12.385E32",
    description:
      "The Sinotruk HOWO A7 is one of China's most exported heavy-duty trucks. Built for demanding conditions across Africa, Southeast Asia, and the Middle East, it offers robust construction, powerful diesel engines, and excellent payload capacity. Widely used in construction, mining, and long-haul logistics.",
    specs: {
      power: "385 hp (283 kW)",
      torque: "1,460 Nm",
      acceleration: "N/A",
      topSpeed: "90 km/h",
      fuelEconomy: "35 L/100 km",
      engineDisplacement: "9.7L Diesel",
      drivetrain: "4x4",
      length: "7,245 mm",
      width: "2,496 mm",
      height: "3,100 mm",
      wheelbase: "3,625 mm",
      weight: "7,300 kg",
      seatingCapacity: 2,
      payloadCapacity: "25,000 kg",
    },
    features: [
      "Air-conditioned cabin",
      "Power steering",
      "ABS braking system",
      "Dual rear wheels",
      "Heavy-duty suspension",
      "Tool kit included",
    ],
    colors: ["White", "Blue", "Yellow"],
    condition: "New",
    availability: "In Stock",
    fobPrice: 32000,
    portOfLoading: "Qingdao / Tianjin",
    handDrive: "LHD",
    shippingEstimate: "30-45 days (Africa), 25-35 days (SE Asia)",
    exportDocs: ["Commercial Invoice", "Packing List", "Bill of Lading", "Certificate of Origin", "Export Customs Clearance"],
  },
  {
    id: "faw-j6p",
    slug: "faw-j6p",
    brand: "FAW",
    model: "J6P",
    year: 2024,
    price: 35000,
    fuel: "Diesel",
    bodyType: "Truck",
    transmission: "Manual",
    image: "/vehicles/faw-j6p.jpg",
    images: ["/vehicles/faw-j6p.jpg"],
    badge: "Popular",
    engine: "CA6DM2-39E31",
    description:
      "The FAW J6P is a premium heavy-duty truck from China's oldest truck manufacturer. Known for its reliability and durability, the J6P is a top choice for fleet operators in developing markets. Features a comfortable cab, strong chassis, and proven powertrain.",
    specs: {
      power: "390 hp (287 kW)",
      torque: "1,500 Nm",
      acceleration: "N/A",
      topSpeed: "95 km/h",
      fuelEconomy: "33 L/100 km",
      engineDisplacement: "11.0L Diesel",
      drivetrain: "4x4",
      length: "7,150 mm",
      width: "2,495 mm",
      height: "3,080 mm",
      wheelbase: "3,600 mm",
      weight: "7,500 kg",
      seatingCapacity: 2,
      payloadCapacity: "28,000 kg",
    },
    features: [
      "Sleeper cab option",
      "Air conditioning",
      "Power windows",
      "Central locking",
      "Retarder braking",
      "Fuel-efficient engine",
    ],
    colors: ["White", "Red", "Blue"],
    condition: "New",
    availability: "In Stock",
    fobPrice: 35000,
    portOfLoading: "Tianjin / Qingdao",
    handDrive: "LHD",
    shippingEstimate: "30-45 days (Africa), 25-35 days (SE Asia)",
    exportDocs: ["Commercial Invoice", "Packing List", "Bill of Lading", "Certificate of Origin", "Export Customs Clearance"],
  },
  {
    id: "dongfeng-captain",
    slug: "dongfeng-captain",
    brand: "Dongfeng",
    model: "Captain D9",
    year: 2024,
    price: 28000,
    fuel: "Diesel",
    bodyType: "Truck",
    transmission: "Manual",
    image: "/vehicles/dongfeng-captain.jpg",
    images: ["/vehicles/dongfeng-captain.jpg"],
    engine: "Cummins ISL9",
    description:
      "The Dongfeng Captain D9 is a versatile medium-duty truck suitable for urban logistics, construction, and regional distribution. Powered by a Cummins engine, it delivers reliable performance with low maintenance costs.",
    specs: {
      power: "270 hp (199 kW)",
      torque: "950 Nm",
      acceleration: "N/A",
      topSpeed: "90 km/h",
      fuelEconomy: "28 L/100 km",
      engineDisplacement: "8.9L Diesel",
      drivetrain: "4x4",
      length: "6,800 mm",
      width: "2,380 mm",
      height: "2,850 mm",
      wheelbase: "3,400 mm",
      weight: "5,200 kg",
      seatingCapacity: 2,
      payloadCapacity: "15,000 kg",
    },
    features: [
      "Cummins engine",
      "Hydraulic power steering",
      "Air brakes",
      "Adjustable seats",
      "USB charging port",
    ],
    colors: ["White", "Blue"],
    condition: "New",
    availability: "In Stock",
    fobPrice: 28000,
    portOfLoading: "Wuhan / Shanghai",
    handDrive: "LHD",
    shippingEstimate: "28-40 days (Africa), 22-30 days (SE Asia)",
    exportDocs: ["Commercial Invoice", "Packing List", "Bill of Lading", "Certificate of Origin"],
  },
  {
    id: "foton-aumark",
    slug: "foton-aumark",
    brand: "Foton",
    model: "Aumark S5",
    year: 2024,
    price: 22000,
    fuel: "Diesel",
    bodyType: "Truck",
    transmission: "Manual",
    image: "/vehicles/foton-aumark.jpg",
    images: ["/vehicles/foton-aumark.jpg"],
    engine: "Cummins ISF3.8",
    description:
      "The Foton Aumark S5 is a light-duty truck ideal for urban delivery and last-mile logistics. Compact design, excellent maneuverability, and low running costs make it perfect for small businesses expanding into Chinese commercial vehicles.",
    specs: {
      power: "156 hp (115 kW)",
      torque: "500 Nm",
      acceleration: "N/A",
      topSpeed: "100 km/h",
      fuelEconomy: "14 L/100 km",
      engineDisplacement: "3.8L Diesel",
      drivetrain: "4x2",
      length: "5,995 mm",
      width: "2,150 mm",
      height: "2,450 mm",
      wheelbase: "3,360 mm",
      weight: "3,200 kg",
      seatingCapacity: 2,
      payloadCapacity: "5,000 kg",
    },
    features: [
      "Cummins engine",
      "Power steering",
      "Air conditioning",
      "Bluetooth audio",
      "Rear parking sensors",
    ],
    colors: ["White", "Silver"],
    condition: "New",
    availability: "In Stock",
    fobPrice: 22000,
    portOfLoading: "Shanghai / Guangzhou",
    handDrive: "LHD",
    shippingEstimate: "25-35 days (Africa), 20-28 days (SE Asia)",
    exportDocs: ["Commercial Invoice", "Packing List", "Bill of Lading", "Certificate of Origin"],
  },

  // ══════════════════════════════════════════════════════════════
  // USED / CERTIFIED PRE-OWNED VEHICLES
  // ══════════════════════════════════════════════════════════════
  {
    id: "used-byd-han-2022",
    slug: "used-byd-han-2022",
    brand: "BYD",
    model: "Han EV (2022)",
    year: 2022,
    price: 18500,
    fuel: "Electric",
    bodyType: "Sedan",
    transmission: "Single-Speed",
    image: "/vehicles/byd-han.jpg",
    images: ["/vehicles/byd-han.jpg", "/vehicles/byd-han-rear.jpg", "/vehicles/byd-han-interior.jpg"],
    badge: "CPO",
    range: "550 km",
    engine: "Dual Motor AWD",
    description:
      "Certified pre-owned 2022 BYD Han EV with 28,000 km. Excellent condition, single owner, full service history. Blade Battery in perfect health. Includes remaining manufacturer warranty. Ideal for buyers seeking premium electric at a lower cost.",
    specs: {
      power: "517 hp (380 kW)",
      torque: "700 Nm",
      acceleration: "3.9s (0-100 km/h)",
      topSpeed: "185 km/h",
      range: "550 km (CLTC)",
      batteryCapacity: "85.4 kWh",
      chargingTime: "25 min (10-80% DC fast)",
      drivetrain: "AWD",
      length: "4,995 mm",
      width: "1,910 mm",
      height: "1,495 mm",
      wheelbase: "2,920 mm",
      weight: "2,100 kg",
      seatingCapacity: 5,
      bootSpace: "410 L",
    },
    features: [
      "Blade Battery (95%+ health)",
      "15.6-inch Rotating Touchscreen",
      "Nappa Leather Interior",
      "Level 2 Autonomous Driving",
      "Full Service History",
      "Remaining Warranty",
    ],
    colors: ["Aurora White"],
    condition: "Used",
    availability: "In Stock",
    mileage: 28000,
    fobPrice: 18500,
    portOfLoading: "Shanghai",
    handDrive: "LHD",
    shippingEstimate: "30-40 days (Africa), 25-35 days (Middle East)",
    exportDocs: ["Commercial Invoice", "Packing List", "Bill of Lading", "Used Vehicle Export Certificate", "Inspection Report"],
  },
  {
    id: "used-toyota-rav4-2021",
    slug: "used-toyota-rav4-2021",
    brand: "Toyota",
    model: "RAV4 (2021)",
    year: 2021,
    price: 14800,
    fuel: "Hybrid",
    bodyType: "SUV",
    transmission: "Automatic",
    image: "/vehicles/rav4.jpg",
    images: ["/vehicles/rav4.jpg", "/vehicles/rav4-rear.jpg", "/vehicles/rav4-interior.jpg"],
    badge: "Value",
    engine: "2.5L Hybrid",
    description:
      "Well-maintained 2021 Toyota RAV4 Hybrid with 35,000 km. Known for bulletproof reliability and excellent fuel economy. Single owner, non-smoking, no accidents. Perfect for export to developing markets where Toyota resale value is highest.",
    specs: {
      power: "219 hp (163 kW)",
      torque: "221 Nm",
      acceleration: "8.1s (0-100 km/h)",
      topSpeed: "180 km/h",
      fuelEconomy: "5.8 L/100 km",
      engineDisplacement: "2.5L Hybrid",
      drivetrain: "AWD",
      length: "4,600 mm",
      width: "1,855 mm",
      height: "1,685 mm",
      wheelbase: "2,690 mm",
      weight: "1,670 kg",
      seatingCapacity: 5,
      bootSpace: "580 L",
    },
    features: [
      "Toyota Safety Sense 2.0",
      "AWD-i",
      "Apple CarPlay",
      "Power Tailgate",
      "No Accident History",
      "Full Service Records",
    ],
    colors: ["Pearl White"],
    condition: "Used",
    availability: "In Stock",
    mileage: 35000,
    fobPrice: 14800,
    portOfLoading: "Tianjin",
    handDrive: "LHD",
    shippingEstimate: "30-40 days (Africa), 25-35 days (Middle East)",
    exportDocs: ["Commercial Invoice", "Packing List", "Bill of Lading", "Used Vehicle Export Certificate", "Inspection Report"],
  },
  {
    id: "used-honda-civic-2023",
    slug: "used-honda-civic-2023",
    brand: "Honda",
    model: "Civic (2023)",
    year: 2023,
    price: 13500,
    fuel: "Petrol",
    bodyType: "Sedan",
    transmission: "Automatic",
    image: "/vehicles/civic.jpg",
    images: ["/vehicles/civic.jpg", "/vehicles/civic-rear.jpg", "/vehicles/civic-interior.jpg"],
    badge: "Low KM",
    engine: "1.5T VTEC",
    description:
      "Low-mileage 2023 Honda Civic with only 12,000 km. Practically new condition. Popular model with strong demand across Africa and Southeast Asia. Honda's reputation for reliability makes this a safe import choice.",
    specs: {
      power: "180 hp (134 kW)",
      torque: "240 Nm",
      acceleration: "7.9s (0-100 km/h)",
      topSpeed: "200 km/h",
      fuelEconomy: "6.0 L/100 km",
      engineDisplacement: "1.5L VTEC Turbo",
      drivetrain: "FWD",
      length: "4,675 mm",
      width: "1,800 mm",
      height: "1,415 mm",
      wheelbase: "2,735 mm",
      weight: "1,330 kg",
      seatingCapacity: 5,
      bootSpace: "420 L",
    },
    features: [
      "Honda Sensing",
      "9-inch Touchscreen",
      "Apple CarPlay & Android Auto",
      "Low Mileage (12k km)",
      "No Accidents",
      "Original Paint",
    ],
    colors: ["Sonic Grey"],
    condition: "Used",
    availability: "In Stock",
    mileage: 12000,
    fobPrice: 13500,
    portOfLoading: "Shanghai",
    handDrive: "LHD",
    shippingEstimate: "28-38 days (Africa), 22-30 days (SE Asia)",
    exportDocs: ["Commercial Invoice", "Packing List", "Bill of Lading", "Used Vehicle Export Certificate", "Inspection Report"],
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Ahmed Khan",
    role: "Import Dealer",
    country: "Pakistan",
    flag: "🇵🇰",
    rating: 5,
    quote:
      "86Connect sourced 12 vehicles for my dealership in Karachi. Every car arrived exactly as inspected. The transparent pricing and professional documentation saved me weeks of hassle.",
    avatar: "https://i.pravatar.cc/120?img=12",
  },
  {
    id: "2",
    name: "David Okonkwo",
    role: "Fleet Manager",
    country: "Nigeria",
    flag: "🇳🇬",
    rating: 5,
    quote:
      "I've imported over 30 cars through 86Connect. Their inspection process is rigorous and shipping to Lagos has always been on time. This is the most reliable export partner I've worked with.",
    avatar: "https://i.pravatar.cc/120?img=33",
  },
  {
    id: "3",
    name: "Rashid Al-Maktoum",
    role: "Private Buyer",
    country: "UAE",
    flag: "🇦🇪",
    rating: 5,
    quote:
      "From quotation to delivery in Dubai, the entire process took 18 days. The BYD Han EV I ordered was in pristine condition. 86Connect handles everything professionally.",
    avatar: "https://i.pravatar.cc/120?img=68",
  },
  {
    id: "4",
    name: "James Mwangi",
    role: "Business Owner",
    country: "Kenya",
    flag: "🇰🇪",
    rating: 5,
    quote:
      "The team at 86Connect understood exactly what I needed. They found the perfect Toyota RAV4 within my budget and handled all the export paperwork. Shipping to Mombasa was seamless.",
    avatar: "https://i.pravatar.cc/120?img=51",
  },
  {
    id: "5",
    name: "Tanaka Hiroshi",
    role: "Auto Reseller",
    country: "Japan",
    flag: "🇯🇵",
    rating: 5,
    quote:
      "Even as a Japanese buyer, sourcing Chinese EVs through 86Connect was effortless. Their English and Chinese support team is responsive 24/7. Highly recommended for serious buyers.",
    avatar: "https://i.pravatar.cc/120?img=15",
  },
  {
    id: "6",
    name: "Sarah Williams",
    role: "Dealer Principal",
    country: "Australia",
    flag: "🇦🇺",
    rating: 5,
    quote:
      "We've built a strong partnership with 86Connect over two years. Their supplier network in China is unmatched, and the quality of vehicles consistently exceeds expectations.",
    avatar: "https://i.pravatar.cc/120?img=44",
  },
];

export const faqs: FAQItem[] = [
  {
    id: "1",
    question: "How does the vehicle sourcing process work?",
    answer:
      "Simply tell us the car you want — brand, model, year, and budget. We leverage our verified supplier network across China to find the best matching vehicle, negotiate the price, and provide you with a detailed quotation within 24 hours.",
  },
  {
    id: "2",
    question: "What payment methods do you accept?",
    answer:
      "We accept bank transfers (T/T), letters of credit (L/C), and PayPal for deposits. A 30% deposit secures your vehicle, with the balance due before shipping. All transactions are transparent and documented.",
  },
  {
    id: "3",
    question: "How long does shipping take?",
    answer:
      "Shipping times vary by destination: 7-14 days to Southeast Asia, 18-30 days to the Middle East, 25-40 days to Africa, and 30-45 days to Europe and Australia. We provide real-time tracking throughout the journey.",
  },
  {
    id: "4",
    question: "Do you inspect vehicles before shipping?",
    answer:
      "Absolutely. Every vehicle undergoes a comprehensive 150-point inspection by our certified technicians before shipment. You receive a detailed inspection report with photos and videos, ensuring complete transparency.",
  },
  {
    id: "5",
    question: "What documents are included with the export?",
    answer:
      "We handle all export documentation including the commercial invoice, packing list, bill of lading, certificate of origin, and export customs clearance. You receive a complete document package for smooth import at your destination.",
  },
  {
    id: "6",
    question: "Is there a warranty on exported vehicles?",
    answer:
      "New vehicles carry the manufacturer's warranty where applicable. For used vehicles, we offer optional extended warranty coverage. Our 150-point inspection ensures every vehicle meets quality standards before export.",
  },
  {
    id: "7",
    question: "Can you handle customs clearance at my destination?",
    answer:
      "While we handle all China-side export customs, we work with trusted partners in most destination countries who can assist with import clearance. We'll connect you with reliable local agents to complete the process smoothly.",
  },
  {
    id: "8",
    question: "What if the vehicle doesn't match the description?",
    answer:
      "Our inspection reports with photos and videos ensure what you see is what you get. In the rare event of a discrepancy, we have a clear resolution process. Your deposit is fully refundable if the vehicle fails inspection.",
  },
];

export const processSteps: ProcessStep[] = [
  {
    step: 1,
    title: "Tell Us the Car",
    description:
      "Share your desired brand, model, year, and budget. The more details you provide, the better we can match your needs.",
    icon: "Search",
  },
  {
    step: 2,
    title: "We Source the Best",
    description:
      "Our team searches our verified supplier network across China to find the perfect vehicle that matches your specifications.",
    icon: "Radar",
  },
  {
    step: 3,
    title: "Receive Quotation",
    description:
      "Get a transparent, itemized quotation within 24 hours — including vehicle cost, inspection, and shipping to your destination.",
    icon: "FileText",
  },
  {
    step: 4,
    title: "Inspection",
    description:
      "Every vehicle undergoes a rigorous 150-point inspection. You receive a detailed report with photos and videos before approval.",
    icon: "ShieldCheck",
  },
  {
    step: 5,
    title: "Shipping",
    description:
      "We handle all export documentation and arrange shipping via RoRo or container, with real-time tracking to your port.",
    icon: "Ship",
  },
  {
    step: 6,
    title: "Delivered",
    description:
      "Your vehicle arrives at the destination port with all documents ready for customs clearance. Drive away with confidence.",
    icon: "CheckCircle2",
  },
];

export const features: Feature[] = [
  {
    id: "suppliers",
    title: "Verified Suppliers",
    description:
      "Direct access to China's most trusted dealerships and manufacturers. Every supplier is vetted for quality and reliability.",
    icon: "BadgeCheck",
  },
  {
    id: "inspection",
    title: "150-Point Inspection",
    description:
      "Certified technicians inspect every vehicle before shipment. You see detailed photos and videos before you commit.",
    icon: "ShieldCheck",
  },
  {
    id: "logistics",
    title: "End-to-End Logistics",
    description:
      "From factory to your port — we manage shipping, tracking, and all export documentation with complete transparency.",
    icon: "Ship",
  },
  {
    id: "pricing",
    title: "Transparent Pricing",
    description:
      "No hidden fees. No surprises. Itemized quotations with vehicle cost, inspection, and shipping clearly separated.",
    icon: "ReceiptText",
  },
  {
    id: "support",
    title: "24/7 Support",
    description:
      "English and Chinese support teams available around the clock. Get answers when you need them, wherever you are.",
    icon: "Headphones",
  },
  {
    id: "compliance",
    title: "Global Compliance",
    description:
      "We handle all export documentation and ensure compliance with international trade regulations for smooth import.",
    icon: "Globe2",
  },
];

export const heroStats = [
  { value: "2000+", label: "Cars Exported", icon: "Car" },
  { value: "40+", label: "Countries", icon: "Globe" },
  { value: "24/7", label: "Support", icon: "Headphones" },
  { value: "100%", label: "Transparent Process", icon: "ShieldCheck" },
];

export const shippingRoutes = [
  // Africa
  { country: "Nigeria", flag: "🇳🇬", x: 50, y: 53 },
  { country: "Ghana", flag: "🇬🇭", x: 48, y: 52 },
  { country: "Kenya", flag: "🇰🇪", x: 58, y: 55 },
  { country: "South Africa", flag: "🇿🇦", x: 52, y: 68 },
  { country: "Egypt", flag: "🇪🇬", x: 56, y: 42 },
  { country: "Tanzania", flag: "🇹🇿", x: 57, y: 57 },
  // Americas
  { country: "USA", flag: "🇺🇸", x: 16, y: 35 },
  { country: "Canada", flag: "🇨🇦", x: 18, y: 28 },
  { country: "Mexico", flag: "🇲🇽", x: 15, y: 45 },
  { country: "Brazil", flag: "🇧🇷", x: 30, y: 62 },
  { country: "Chile", flag: "🇨🇱", x: 26, y: 72 },
  { country: "Colombia", flag: "🇨🇴", x: 24, y: 52 },
  // Europe
  { country: "Germany", flag: "🇩🇪", x: 50, y: 28 },
  { country: "UK", flag: "🇬🇧", x: 47, y: 25 },
  { country: "Netherlands", flag: "🇳🇱", x: 49, y: 26 },
  { country: "France", flag: "🇫🇷", x: 48, y: 30 },
  { country: "Spain", flag: "🇪🇸", x: 46, y: 33 },
  { country: "Italy", flag: "🇮🇹", x: 51, y: 32 },
];

export const navLinks = [
  { label: "Home", href: "#home" },
  { label: "Inventory", href: "/inventory" },
  { label: "Brands", href: "/brands" },
  { label: "About", href: "/about" },
  { label: "How It Works", href: "#how-it-works" },
  { label: "Why Us", href: "#why-us" },
  { label: "FAQ", href: "#faq" },
  { label: "Contact", href: "#contact" },
];
