"use client";

import { useEffect, useState } from "react";
import { Trash2, FileText, Download, X, ExternalLink } from "lucide-react";

const QUOTE_STATUSES = ["new", "contacted", "closed"] as const;

const STATUS_COLORS: Record<string, string> = {
  new: "bg-blue-100 text-blue-700",
  contacted: "bg-yellow-100 text-yellow-700",
  closed: "bg-green-100 text-green-700",
};

function generateDocxHtml(q: Record<string, unknown>): string {
  const images = (q.referenceImages as string[]) ?? [];
  const imageRows = images.length > 0
    ? images.map((url, i) => {
        const isImage = /\.(jpg|jpeg|png|gif|webp|svg|bmp)/i.test(url) || url.includes("cloudinary");
        return isImage
          ? `<tr><td style="padding:8px 0;font-weight:bold;color:#555;">Image ${i + 1}:</td><td><img src="${url}" style="max-width:400px;max-height:300px;display:block;margin:8px 0;" /></td></tr>`
          : `<tr><td style="padding:8px 0;font-weight:bold;color:#555;">Attachment ${i + 1}:</td><td><a href="${url}">${url}</a></td></tr>`;
      }).join("")
    : `<tr><td style="padding:8px 0;font-weight:bold;color:#555;">Images:</td><td style="color:#999;">None</td></tr>`;

  return `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><title>Quote - ${q.name || "Submission"}</title></head>
<body style="font-family:Arial,sans-serif;max-width:700px;margin:40px auto;color:#222;">
  <h1 style="border-bottom:2px solid #2563eb;padding-bottom:8px;color:#2563eb;">Quote Submission</h1>
  <table style="width:100%;border-collapse:collapse;font-size:14px;">
    <tr><td style="padding:8px 0;font-weight:bold;color:#555;width:140px;">Name:</td><td>${q.name || "—"}</td></tr>
    <tr><td style="padding:8px 0;font-weight:bold;color:#555;">Email:</td><td>${q.email || "—"}</td></tr>
    <tr><td style="padding:8px 0;font-weight:bold;color:#555;">WhatsApp:</td><td>${q.whatsapp || "—"}</td></tr>
    <tr><td style="padding:8px 0;font-weight:bold;color:#555;">Country:</td><td>${q.country || "—"}</td></tr>
    <tr><td style="padding:8px 0;font-weight:bold;color:#555;">Vehicle Brand:</td><td>${q.vehicleBrand || "—"}</td></tr>
    <tr><td style="padding:8px 0;font-weight:bold;color:#555;">Model:</td><td>${q.model || "—"}</td></tr>
    ${q.vehicleSlug ? `<tr><td style="padding:8px 0;font-weight:bold;color:#555;">Vehicle Page:</td><td><a href="/inventory/${q.vehicleSlug}">View ${q.vehicleBrand} ${q.model}</a></td></tr>` : ""}
    <tr><td style="padding:8px 0;font-weight:bold;color:#555;">Budget:</td><td>${q.budget || "—"}</td></tr>
    <tr><td style="padding:8px 0;font-weight:bold;color:#555;">Status:</td><td>${q.status || "new"}</td></tr>
    <tr><td style="padding:8px 0;font-weight:bold;color:#555;">Date:</td><td>${new Date(q.createdAt as string).toLocaleString()}</td></tr>
  </table>
  <h2 style="border-bottom:1px solid #ddd;padding-bottom:4px;margin-top:24px;color:#333;">Message</h2>
  <p style="white-space:pre-wrap;line-height:1.6;background:#f9fafb;padding:16px;border-radius:8px;font-size:14px;">${q.message || "No message"}</p>
  <h2 style="border-bottom:1px solid #ddd;padding-bottom:4px;margin-top:24px;color:#333;">Images</h2>
  <table style="width:100%;border-collapse:collapse;font-size:14px;">${imageRows}</table>
  <p style="margin-top:24px;color:#999;font-size:12px;">Generated by 86Connect Cars Admin — ${new Date().toISOString()}</p>
</body>
</html>`;
}

function downloadDocx(html: string, filename: string) {
  const blob = new Blob([html], { type: "application/msword" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export default function AdminQuotes() {
  const [quotes, setQuotes] = useState<Record<string, unknown>[]>([]);
  const [loading, setLoading] = useState(true);
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [deleteId, setDeleteId] = useState<string | null>(null);
  const [viewId, setViewId] = useState<string | null>(null);
  const [deleteLoading, setDeleteLoading] = useState(false);

  useEffect(() => {
    fetch("/api/quotes")
      .then((r) => r.json())
      .then((data) => { setQuotes(Array.isArray(data) ? data.reverse() : []); setLoading(false); });
  }, []);

  const updateField = async (id: string, field: string, value: string) => {
    await fetch("/api/quotes", {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ id, [field]: value }),
    });
    setQuotes((prev) => prev.map((q) => q.id === id ? { ...q, [field]: value } : q));
  };

  const handleDelete = async (id: string) => {
    setDeleteLoading(true);
    try {
      await fetch(`/api/quotes?id=${encodeURIComponent(id)}`, { method: "DELETE" });
      setQuotes((prev) => prev.filter((q) => q.id !== id));
      setDeleteId(null);
      if (expandedId === id) setExpandedId(null);
      if (viewId === id) setViewId(null);
    } finally {
      setDeleteLoading(false);
    }
  };

  const quote = viewId ? quotes.find((q) => q.id === viewId) : null;
  const deleteTarget = deleteId ? quotes.find((q) => q.id === deleteId) : null;

  return (
    <div>
      <h1 className="text-2xl font-bold text-gray-900 mb-6">Quote Submissions</h1>

      {loading ? (
        <p className="text-gray-500">Loading...</p>
      ) : quotes.length === 0 ? (
        <p className="text-gray-500">No quotes yet.</p>
      ) : (
        <div className="space-y-4">
          {quotes.map((q) => {
            const id = q.id as string;
            const isExpanded = expandedId === id;
            return (
              <div key={id} className="rounded-xl bg-white border border-[#e6f4f8] shadow-sm hover:shadow-md hover:border-[#b8e4f0] transition-all">
                <div className="px-4 py-2.5">
                  <div className="flex items-center justify-between gap-3">
                    <div className="flex-1 min-w-0 flex items-center gap-3">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-1.5 flex-wrap">
                          <h3 className="text-sm font-semibold text-gray-900">{q.name as string}</h3>
                          <span className={`rounded-full px-1.5 py-px text-[10px] font-medium ${STATUS_COLORS[q.status as string] || ""}`}>
                            {q.status as string}
                          </span>
                          {q.userId ? (
                            <span className="rounded-full bg-[#e0f0ff] px-1.5 py-px text-[10px] font-medium text-[#087ea4]">Registered</span>
                          ) : (
                            <span className="rounded-full bg-gray-50 px-1.5 py-px text-[10px] font-medium text-gray-400">Guest</span>
                          )}
                        </div>
                        <div className="flex items-center gap-2 mt-0.5">
                          <p className="text-[11px] text-gray-500">{q.email as string}</p>
                          <span className="text-[11px] font-medium text-gray-700">{String(q.vehicleBrand)} {String(q.model)}</span>
                          {q.vehicleSlug && (
                            <a
                              href={`/inventory/${q.vehicleSlug}`}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="text-[10px] font-medium text-[#087ea4] hover:underline flex items-center gap-0.5"
                            >
                              <ExternalLink className="h-2.5 w-2.5" />
                              View
                            </a>
                          )}
                          <span className="text-[10px] text-gray-300">{new Date(q.createdAt as string).toLocaleDateString()}</span>
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center gap-1 shrink-0">
                      <button
                        type="button"
                        onClick={() => setViewId(id)}
                        className="rounded-lg bg-[#087ea4] px-3 py-1.5 text-[11px] font-medium text-white hover:bg-[#149eca] transition-colors flex items-center gap-1"
                      >
                        <FileText className="h-3 w-3" />
                        View
                      </button>
                      <button
                        type="button"
                        onClick={() => setExpandedId(isExpanded ? null : id)}
                        className="rounded-lg border border-gray-200 px-2.5 py-1.5 text-[11px] font-medium text-gray-600 hover:bg-gray-50 hover:border-gray-300 transition-colors"
                      >
                        {isExpanded ? "Hide" : "Manage"}
                      </button>
                      <button
                        type="button"
                        onClick={() => setDeleteId(id)}
                        className="rounded-lg border border-red-100 px-2 py-1.5 text-[11px] font-medium text-red-500 hover:bg-red-50 hover:border-red-200 transition-colors"
                      >
                        <Trash2 className="h-3 w-3" />
                      </button>
                      <button
                        type="button"
                        onClick={() => downloadDocx(generateDocxHtml(q), `quote-${id}.doc`)}
                        className="rounded-lg border border-[#e6f4f8] px-2 py-1.5 text-[11px] font-medium text-[#087ea4] hover:bg-[#f0f9fc] hover:border-[#b8e4f0] transition-colors"
                      >
                        <Download className="h-3 w-3" />
                      </button>
                    </div>
                  </div>
                </div>

                {/* Expanded panel — quote status controls */}
                {isExpanded && (
                  <div className="border-t border-gray-100 bg-gray-50/50 px-4 py-3">
                    <div>
                      <label className="block text-[10px] font-semibold text-gray-400 mb-1.5">Quote Status</label>
                      <div className="flex flex-wrap gap-1">
                        {QUOTE_STATUSES.map((s) => (
                          <button
                            key={s}
                            type="button"
                            onClick={() => updateField(id, "status", s)}
                            className={`rounded-full px-2 py-1 text-[10px] font-medium transition-all ${
                              q.status === s
                                ? `${STATUS_COLORS[s]} ring-2 ring-offset-1`
                                : "bg-white border border-gray-200 text-gray-500 hover:bg-gray-50"
                            }`}
                          >
                            {s.charAt(0).toUpperCase() + s.slice(1)}
                          </button>
                        ))}
                      </div>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}

      {/* View modal */}
      {viewId && quote && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm" onClick={() => setViewId(null)}>
          <div className="relative max-h-[85vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white shadow-2xl border border-[#e6f4f8]" onClick={(e) => e.stopPropagation()}>
            {/* Header */}
            <div className="sticky top-0 bg-gradient-to-r from-[#087ea4] to-[#149eca] px-6 py-4 rounded-t-2xl z-10">
              <div className="flex items-center justify-between">
                <div>
                  <h2 className="text-lg font-bold text-white">{quote.name as string}</h2>
                  <p className="text-[11px] text-white/70">{new Date(quote.createdAt as string).toLocaleString()}</p>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={() => downloadDocx(generateDocxHtml(quote), `quote-${viewId}.doc`)}
                    className="rounded-lg bg-white/20 backdrop-blur px-3 py-1.5 text-[11px] font-medium text-white hover:bg-white/30 transition-colors flex items-center gap-1.5"
                  >
                    <Download className="h-3 w-3" />
                    Download
                  </button>
                  <button type="button" onClick={() => setViewId(null)} className="rounded-lg p-1.5 text-white/70 hover:bg-white/10 hover:text-white transition-colors">
                    <X className="h-4 w-4" />
                  </button>
                </div>
              </div>
            </div>

            {/* Body */}
            <div className="px-6 py-5">
              {/* Status badges */}
              <div className="flex items-center gap-2 mb-5">
                <span className={`rounded-full px-2 py-0.5 text-[11px] font-medium ${STATUS_COLORS[quote.status as string] || ""}`}>
                  {quote.status as string}
                </span>
                {quote.userId ? (
                  <span className="rounded-full bg-[#e0f0ff] px-2 py-0.5 text-[11px] font-medium text-[#087ea4]">Registered User</span>
                ) : (
                  <span className="rounded-full bg-gray-50 px-2 py-0.5 text-[11px] font-medium text-gray-400">Guest</span>
                )}
              </div>

              {/* Details grid */}
              <div className="grid grid-cols-2 gap-x-6 gap-y-3 mb-5">
                <div>
                  <span className="text-[10px] font-semibold uppercase tracking-wider text-[#087ea4]">Email</span>
                  <p className="text-sm text-gray-700 mt-0.5">{quote.email as string || "—"}</p>
                </div>
                <div>
                  <span className="text-[10px] font-semibold uppercase tracking-wider text-[#087ea4]">WhatsApp</span>
                  <p className="text-sm text-gray-700 mt-0.5">{quote.whatsapp as string || "—"}</p>
                </div>
                <div>
                  <span className="text-[10px] font-semibold uppercase tracking-wider text-[#087ea4]">Country</span>
                  <p className="text-sm text-gray-700 mt-0.5">{quote.country as string || "—"}</p>
                </div>
                <div>
                  <span className="text-[10px] font-semibold uppercase tracking-wider text-[#087ea4]">Budget</span>
                  <p className="text-sm text-gray-700 mt-0.5">{quote.budget as string || "—"}</p>
                </div>
                <div>
                  <span className="text-[10px] font-semibold uppercase tracking-wider text-[#087ea4]">Vehicle Brand</span>
                  <p className="text-sm font-semibold text-gray-900 mt-0.5">{quote.vehicleBrand as string || "—"}</p>
                </div>
                <div>
                  <span className="text-[10px] font-semibold uppercase tracking-wider text-[#087ea4]">Model</span>
                  <p className="text-sm text-gray-700 mt-0.5">{quote.model as string || "—"}</p>
                </div>
                {quote.vehicleSlug && (
                  <div className="col-span-2">
                    <span className="text-[10px] font-semibold uppercase tracking-wider text-[#087ea4]">Vehicle Page</span>
                    <p className="text-sm mt-0.5">
                      <a
                        href={`/inventory/${quote.vehicleSlug}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-[#087ea4] hover:underline flex items-center gap-1"
                      >
                        <ExternalLink className="h-3.5 w-3.5" />
                        View {quote.vehicleBrand} {quote.model}
                      </a>
                    </p>
                  </div>
                )}
              </div>

              {/* Message */}
              {quote.message ? (
                <div className="mb-5">
                  <h3 className="text-[10px] font-semibold uppercase tracking-wider text-[#087ea4] mb-2">Message</h3>
                  <div className="bg-[#f0f9fc] rounded-xl p-4 border border-[#e6f4f8]">
                    <p className="text-sm text-gray-700 whitespace-pre-wrap leading-relaxed">{quote.message as string}</p>
                  </div>
                </div>
              ) : null}

              {/* Images */}
              {(quote.referenceImages as string[])?.length > 0 && (
                <div>
                  <h3 className="text-[10px] font-semibold uppercase tracking-wider text-[#087ea4] mb-2">
                    Images ({(quote.referenceImages as string[]).length})
                  </h3>
                  <div className="flex flex-wrap gap-2">
                    {(quote.referenceImages as string[]).map((url, i) => (
                      <a key={i} href={url} target="_blank" rel="noopener noreferrer" className="block">
                        <img src={url} alt={`Reference ${i + 1}`} className="h-20 w-20 rounded-xl object-cover border-2 border-[#e6f4f8] hover:border-[#087ea4] hover:opacity-90 transition-all" />
                      </a>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Delete confirmation modal */}
      {deleteId && deleteTarget && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm" onClick={() => !deleteLoading && setDeleteId(null)}>
          <div className="w-full max-w-sm rounded-2xl bg-white p-6 shadow-2xl border border-[#e6f4f8]" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center gap-3 mb-4">
              <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-red-50">
                <Trash2 className="h-5 w-5 text-red-500" />
              </div>
              <h2 className="text-lg font-bold text-gray-900">Delete Quote?</h2>
            </div>
            <p className="text-sm text-gray-600 mb-1">
              This will permanently delete the quote from <strong>{deleteTarget.name as string}</strong>.
            </p>
            <p className="text-xs text-red-500 mb-5">This action cannot be undone.</p>
            <div className="flex justify-end gap-3">
              <button
                type="button"
                onClick={() => setDeleteId(null)}
                disabled={deleteLoading}
                className="rounded-lg border border-gray-200 px-4 py-2 text-sm font-medium text-gray-600 hover:bg-gray-50 disabled:opacity-50 transition-colors"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={() => handleDelete(deleteId)}
                disabled={deleteLoading}
                className="rounded-lg bg-red-500 px-4 py-2 text-sm font-medium text-white hover:bg-red-600 disabled:opacity-50 transition-colors"
              >
                {deleteLoading ? "Deleting..." : "Delete"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}