"use client";

import { useEffect, useState } from "react";
import { Trash2, FileText, Download, X } from "lucide-react";

const QUOTE_STATUSES = ["new", "contacted", "closed"] as const;
const DELIVERY_STATUSES = ["pending", "received", "in_transit", "shipped", "delivered"] as const;

const DELIVERY_LABELS: Record<string, string> = {
  pending: "Pending",
  received: "Order Received",
  in_transit: "In Transit",
  shipped: "Shipped",
  delivered: "Delivered",
};

const DELIVERY_COLORS: Record<string, string> = {
  pending: "bg-gray-100 text-gray-700",
  received: "bg-blue-100 text-blue-700",
  in_transit: "bg-yellow-100 text-yellow-700",
  shipped: "bg-purple-100 text-purple-700",
  delivered: "bg-green-100 text-green-700",
};

const STATUS_COLORS: Record<string, string> = {
  new: "bg-blue-100 text-blue-700",
  contacted: "bg-yellow-100 text-yellow-700",
  closed: "bg-green-100 text-green-700",
};

function generateDocxHtml(q: Record<string, unknown>): string {
  const images = (q.referenceImages as string[]) ?? [];
  const imageRows = images.length > 0
    ? images.map((url, i) => {
        const isImage = /\.(jpg|jpeg|png|gif|webp|svg|bmp)/i.test(url) || url.includes("cloudinary");
        return isImage
          ? `<tr><td style="padding:8px 0;font-weight:bold;color:#555;">Image ${i + 1}:</td><td><img src="${url}" style="max-width:400px;max-height:300px;display:block;margin:8px 0;" /></td></tr>`
          : `<tr><td style="padding:8px 0;font-weight:bold;color:#555;">Attachment ${i + 1}:</td><td><a href="${url}">${url}</a></td></tr>`;
      }).join("")
    : `<tr><td style="padding:8px 0;font-weight:bold;color:#555;">Images:</td><td style="color:#999;">None</td></tr>`;

  return `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><title>Quote - ${q.name || "Submission"}</title></head>
<body style="font-family:Arial,sans-serif;max-width:700px;margin:40px auto;color:#222;">
  <h1 style="border-bottom:2px solid #2563eb;padding-bottom:8px;color:#2563eb;">Quote Submission</h1>
  <table style="width:100%;border-collapse:collapse;font-size:14px;">
    <tr><td style="padding:8px 0;font-weight:bold;color:#555;width:140px;">Name:</td><td>${q.name || "—"}</td></tr>
    <tr><td style="padding:8px 0;font-weight:bold;color:#555;">Email:</td><td>${q.email || "—"}</td></tr>
    <tr><td style="padding:8px 0;font-weight:bold;color:#555;">WhatsApp:</td><td>${q.whatsapp || "—"}</td></tr>
    <tr><td style="padding:8px 0;font-weight:bold;color:#555;">Country:</td><td>${q.country || "—"}</td></tr>
    <tr><td style="padding:8px 0;font-weight:bold;color:#555;">Vehicle Brand:</td><td>${q.vehicleBrand || "—"}</td></tr>
    <tr><td style="padding:8px 0;font-weight:bold;color:#555;">Model:</td><td>${q.model || "—"}</td></tr>
    <tr><td style="padding:8px 0;font-weight:bold;color:#555;">Budget:</td><td>${q.budget || "—"}</td></tr>
    <tr><td style="padding:8px 0;font-weight:bold;color:#555;">Status:</td><td>${q.status || "new"}</td></tr>
    <tr><td style="padding:8px 0;font-weight:bold;color:#555;">Date:</td><td>${new Date(q.createdAt as string).toLocaleString()}</td></tr>
  </table>
  <h2 style="border-bottom:1px solid #ddd;padding-bottom:4px;margin-top:24px;color:#333;">Message</h2>
  <p style="white-space:pre-wrap;line-height:1.6;background:#f9fafb;padding:16px;border-radius:8px;font-size:14px;">${q.message || "No message"}</p>
  <h2 style="border-bottom:1px solid #ddd;padding-bottom:4px;margin-top:24px;color:#333;">Images</h2>
  <table style="width:100%;border-collapse:collapse;font-size:14px;">${imageRows}</table>
  <p style="margin-top:24px;color:#999;font-size:12px;">Generated by 86Connect Cars Admin — ${new Date().toISOString()}</p>
</body>
</html>`;
}

function downloadDocx(html: string, filename: string) {
  const blob = new Blob([html], { type: "application/msword" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export default function AdminQuotes() {
  const [quotes, setQuotes] = useState<Record<string, unknown>[]>([]);
  const [loading, setLoading] = useState(true);
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [deleteId, setDeleteId] = useState<string | null>(null);
  const [viewId, setViewId] = useState<string | null>(null);
  const [deleteLoading, setDeleteLoading] = useState(false);

  useEffect(() => {
    fetch("/api/quotes")
      .then((r) => r.json())
      .then((data) => { setQuotes(Array.isArray(data) ? data.reverse() : []); setLoading(false); });
  }, []);

  const updateField = async (id: string, field: string, value: string) => {
    await fetch("/api/quotes", {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ id, [field]: value }),
    });
    setQuotes((prev) => prev.map((q) => q.id === id ? { ...q, [field]: value } : q));
  };

  const handleDelete = async (id: string) => {
    setDeleteLoading(true);
    try {
      await fetch(`/api/quotes?id=${encodeURIComponent(id)}`, { method: "DELETE" });
      setQuotes((prev) => prev.filter((q) => q.id !== id));
      setDeleteId(null);
      if (expandedId === id) setExpandedId(null);
      if (viewId === id) setViewId(null);
    } finally {
      setDeleteLoading(false);
    }
  };

  const quote = viewId ? quotes.find((q) => q.id === viewId) : null;
  const deleteTarget = deleteId ? quotes.find((q) => q.id === deleteId) : null;

  return (
    <div>
      <h1 className="text-2xl font-bold text-gray-900 mb-6">Quote Submissions</h1>

      {loading ? (
        <p className="text-gray-500">Loading...</p>
      ) : quotes.length === 0 ? (
        <p className="text-gray-500">No quotes yet.</p>
      ) : (
        <div className="space-y-4">
          {quotes.map((q) => {
            const id = q.id as string;
            const isExpanded = expandedId === id;
            const deliveryStatus = (q.deliveryStatus as string) || "pending";
            const images = (q.referenceImages as string[]) ?? [];
            return (
              <div key={id} className="rounded-xl bg-white border border-gray-200 shadow-sm">
                {/* Top row — always visible */}
                <div className="p-5">
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-1">
                        <h3 className="text-sm font-semibold text-gray-900">{q.name as string}</h3>
                        <span className={`rounded-full px-2 py-0.5 text-xs font-medium ${STATUS_COLORS[q.status as string] || ""}`}>
                          {q.status as string}
                        </span>
                        <span className={`rounded-full px-2 py-0.5 text-xs font-medium ${DELIVERY_COLORS[deliveryStatus] || ""}`}>
                          {DELIVERY_LABELS[deliveryStatus] || deliveryStatus}
                        </span>
                        {q.userId ? (
                          <span className="rounded-full bg-indigo-50 px-2 py-0.5 text-xs font-medium text-indigo-700">
                            Registered
                          </span>
                        ) : (
                          <span className="rounded-full bg-gray-50 px-2 py-0.5 text-xs font-medium text-gray-500">
                            Guest
                          </span>
                        )}
                      </div>
                      <p className="text-xs text-gray-500 mb-2">
                        {q.email as string} • {q.whatsapp as string} • {q.country as string}
                      </p>
                      <p className="text-xs text-gray-500 mb-2">
                        Vehicle: <span className="font-medium text-gray-700">{String(q.vehicleBrand)} {String(q.model)}</span>
                        {q.budget ? <span> • Budget: {String(q.budget)}</span> : null}
                      </p>
                      {q.message ? (
                        <p className="text-sm text-gray-700 bg-gray-50 rounded-lg p-3 mt-2">{String(q.message)}</p>
                      ) : null}
                    </div>
                    <div className="flex items-center gap-2">
                      <button
                        type="button"
                        onClick={() => setViewId(id)}
                        className="rounded-lg border border-gray-300 px-3 py-1.5 text-xs font-medium text-gray-700 hover:bg-gray-50 flex items-center gap-1"
                      >
                        <FileText className="h-3.5 w-3.5" />
                        View
                      </button>
                      <button
                        type="button"
                        onClick={() => setExpandedId(isExpanded ? null : id)}
                        className="rounded-lg border border-gray-300 px-3 py-1.5 text-xs font-medium text-gray-700 hover:bg-gray-50"
                      >
                        {isExpanded ? "Hide" : "Manage"}
                      </button>
                      <button
                        type="button"
                        onClick={() => setDeleteId(id)}
                        className="rounded-lg border border-red-200 px-2.5 py-1.5 text-xs font-medium text-red-600 hover:bg-red-50"
                      >
                        <Trash2 className="h-3.5 w-3.5" />
                      </button>
                    </div>
                  </div>
                  <p className="text-[10px] text-gray-400 mt-2">
                    {new Date(q.createdAt as string).toLocaleString()}
                  </p>
                </div>

                {/* Expanded panel — quote status + delivery status controls */}
                {isExpanded && (
                  <div className="border-t border-gray-100 bg-gray-50/50 p-5">
                    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                      <div>
                        <label className="block text-xs font-semibold text-gray-600 mb-2">Quote Status</label>
                        <div className="flex flex-wrap gap-1.5">
                          {QUOTE_STATUSES.map((s) => (
                            <button
                              key={s}
                              type="button"
                              onClick={() => updateField(id, "status", s)}
                              className={`rounded-full px-3 py-1.5 text-xs font-medium transition-all ${
                                q.status === s
                                  ? `${STATUS_COLORS[s]} ring-2 ring-offset-1`
                                  : "bg-white border border-gray-200 text-gray-600 hover:bg-gray-50"
                              }`}
                            >
                              {s.charAt(0).toUpperCase() + s.slice(1)}
                            </button>
                          ))}
                        </div>
                      </div>

                      <div>
                        <label className="block text-xs font-semibold text-gray-600 mb-2">Delivery Tracking</label>
                        <div className="flex flex-wrap gap-1.5">
                          {DELIVERY_STATUSES.map((s) => (
                            <button
                              key={s}
                              type="button"
                              onClick={() => updateField(id, "deliveryStatus", s)}
                              className={`rounded-full px-3 py-1.5 text-xs font-medium transition-all ${
                                deliveryStatus === s
                                  ? `${DELIVERY_COLORS[s]} ring-2 ring-offset-1`
                                  : "bg-white border border-gray-200 text-gray-600 hover:bg-gray-50"
                              }`}
                            >
                              {DELIVERY_LABELS[s]}
                            </button>
                          ))}
                        </div>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}

      {/* View modal */}
      {viewId && quote && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm" onClick={() => setViewId(null)}>
          <div className="relative max-h-[85vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-xl" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-bold text-gray-900">Quote Details</h2>
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={() => downloadDocx(generateDocxHtml(quote), `quote-${viewId}.doc`)}
                  className="rounded-lg bg-blue-600 px-4 py-2 text-xs font-medium text-white hover:bg-blue-700 flex items-center gap-1.5"
                >
                  <Download className="h-3.5 w-3.5" />
                  Download DOCX
                </button>
                <button type="button" onClick={() => setViewId(null)} className="rounded-lg p-1.5 text-gray-400 hover:bg-gray-100 hover:text-gray-600">
                  <X className="h-4 w-4" />
                </button>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-3 mb-4">
              <div><span className="text-xs font-medium text-gray-500">Name</span><p className="text-sm font-semibold text-gray-900">{quote.name as string || "—"}</p></div>
              <div><span className="text-xs font-medium text-gray-500">Email</span><p className="text-sm text-gray-700">{quote.email as string || "—"}</p></div>
              <div><span className="text-xs font-medium text-gray-500">WhatsApp</span><p className="text-sm text-gray-700">{quote.whatsapp as string || "—"}</p></div>
              <div><span className="text-xs font-medium text-gray-500">Country</span><p className="text-sm text-gray-700">{quote.country as string || "—"}</p></div>
              <div><span className="text-xs font-medium text-gray-500">Vehicle Brand</span><p className="text-sm font-semibold text-gray-900">{quote.vehicleBrand as string || "—"}</p></div>
              <div><span className="text-xs font-medium text-gray-500">Model</span><p className="text-sm text-gray-700">{quote.model as string || "—"}</p></div>
              <div><span className="text-xs font-medium text-gray-500">Budget</span><p className="text-sm text-gray-700">{quote.budget as string || "—"}</p></div>
              <div><span className="text-xs font-medium text-gray-500">Date</span><p className="text-sm text-gray-700">{new Date(quote.createdAt as string).toLocaleString()}</p></div>
            </div>

            <div className="mb-4">
              <h3 className="text-xs font-medium text-gray-500 mb-1">Message</h3>
              <p className="text-sm text-gray-700 bg-gray-50 rounded-lg p-3 whitespace-pre-wrap">{quote.message as string || "No message"}</p>
            </div>

            {(quote.referenceImages as string[])?.length > 0 && (
              <div>
                <h3 className="text-xs font-medium text-gray-500 mb-2">Images</h3>
                <div className="flex flex-wrap gap-2">
                  {(quote.referenceImages as string[]).map((url, i) => (
                    <a key={i} href={url} target="_blank" rel="noopener noreferrer" className="block">
                      <img src={url} alt={`Reference ${i + 1}`} className="h-24 w-24 rounded-lg object-cover border border-gray-200 hover:opacity-80 transition-opacity" />
                    </a>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Delete confirmation modal */}
      {deleteId && deleteTarget && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm" onClick={() => !deleteLoading && setDeleteId(null)}>
          <div className="w-full max-w-sm rounded-2xl bg-white p-6 shadow-xl" onClick={(e) => e.stopPropagation()}>
            <h2 className="text-lg font-bold text-gray-900 mb-2">Delete Quote?</h2>
            <p className="text-sm text-gray-600 mb-1">
              This will permanently delete the quote from <strong>{deleteTarget.name as string}</strong>.
            </p>
            <p className="text-xs text-red-500 mb-5">This action cannot be undone.</p>
            <div className="flex justify-end gap-3">
              <button
                type="button"
                onClick={() => setDeleteId(null)}
                disabled={deleteLoading}
                className="rounded-lg border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-50"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={() => handleDelete(deleteId)}
                disabled={deleteLoading}
                className="rounded-lg bg-red-600 px-4 py-2 text-sm font-medium text-white hover:bg-red-700 disabled:opacity-50"
              >
                {deleteLoading ? "Deleting..." : "Delete"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}